env:
#- CKAN_VERSION=release-v2.3-latest    XXX: disable one until clean db works
- CKAN_VERSION=release-v2.4-latest
- CKAN_VERSION=release-v2.5-latest
- CKAN_VERSION=release-v2.6-latest
- CKAN_VERSION=dev-v2.6

command:
- cd ckan; git reset --hard; git checkout $CKAN_VERSION
- sed -i -e 's/.*datastore.read_url.*/ckan.datastore.read_url = postgresql:\/\/datastore_default:pass@\/datastore_test/' ckan/test-core.ini
- sed -i -e 's/solr_url.*/solr_url = http:\/\/127.0.0.1:8983\/solr\/ckan/' ckan/test-core.ini
- cp ckan/ckan/public/base/css/main.css ckan/ckan/public/base/css/main.debug.css
- [ "$CKAN_VERSION" != "release-v2.5-latest" ] || pip install html5lib==0.999  # FIXME remove this terrible workaround
- pip install -U setuptools
- pip install -q -r ckan/requirements.txt --allow-all-external
- pip install -q -r ckan/dev-requirements.txt --allow-all-external
- cd ckan; python setup.py develop
- cd ckan; paster db init -c test-core.ini
- pip install -q -r test-requirements.txt --allow-all-external
- nosetests --with-pylons=subdir/test_subclass.ini --nologcapture ckanext.scheming.tests.test_dataset_display ckanext.scheming.tests.test_form:TestDatasetFormNew ckanext.scheming.tests.test_dataset_logic
- nosetests --with-pylons=subdir/test.ini --nologcapture
